### ISSUE TITLE
Stack pop () doesn't work sometimes

### ISSUE THREAD

**Issue by SonnyRajagopalan** [eyas-ranjous/datastructures-js#31]
Hello, I had high hopes for this package; however, I lost considerable time on a bug that is present in your stack data structure. I hope you can fix this, as I think this is a valuable package.

I eventually went with something simpler, like in https://stackoverflow.com/questions/1590247/how-do-you-implement-a-stack-and-a-queue-in-javascript.

The specific issue is that _sometimes_ the `pop ()` doesn't work correctly. It gets the value of the last inserted item, but leaves the top element in the stack, effectively functioning like a `peek ()`.

**Comment by eyas-ranjous** [comment]
Hi @SonnyRajagopalan thanks for your feedback. 

The stack and queue are implemented to only remove elements when the dequeueing or popping has reached half the size of the them and they use an offset index for this purpose to track where the they should dequeue/pop.
this is intentional to work with big data where you have heavy operations on the queue or stack, and continuously removing an element from the internal array can cause a significant bad performance especially in javascript. 

So based on that, if you have a stack of 10 elements, the removal in the internal array will happen when you have popped at least 5 elements, at this specific point the top 5 elements will be removed all together using one operation, however, `.peek()` will be working always correctly because it uses the current offset index that tracks the next element that should be popped.

So this is an enhanced implementation of the stack and queue implementations.

Can you please post me the code that is causing the issue so I can see where this is coming from and we can discuss it,

Thanks.
